import { Component, input, output, signal } from '@angular/core'; import { FileText, LucideAngularModule, UploadCloud, X } from 'lucide-angular';
@Component({selector:'app-resume-upload',standalone:true,imports:[LucideAngularModule],template:`
<section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-soft dark:border-slate-700 dark:bg-slate-900" aria-labelledby="upload-title">
 <div class="mb-4 flex items-center justify-between"><div><p class="text-xs font-bold uppercase tracking-[.18em] text-brand-600">New analysis</p><h2 id="upload-title" class="mt-1 text-lg font-bold">Upload your resume</h2></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-500 dark:bg-slate-800">PDF · DOCX</span></div>
 @if (!selectedFile()) {<button type="button" class="group flex min-h-52 w-full flex-col items-center justify-center rounded-2xl border-2 border-dashed p-6 text-center transition" [class.border-brand-500]="isDragging()" [class.bg-brand-50]="isDragging()" [class.border-slate-200]="!isDragging()" (dragover)="onDragOver($event)" (dragleave)="isDragging.set(false)" (drop)="onDrop($event)" (click)="fileInput.click()">
   <span class="mb-4 grid size-14 place-items-center rounded-2xl bg-brand-50 text-brand-600 transition group-hover:scale-105"><lucide-icon [img]="UploadCloud" [size]="25" /></span><strong class="text-sm">Drop your resume here</strong><span class="mt-1 text-xs text-slate-500">or <span class="font-semibold text-brand-600">browse your files</span> · Max 10 MB</span></button>
   <input #fileInput class="hidden" type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" (change)="onFileInput($event)">
 } @else {<div class="rounded-2xl border border-brand-100 bg-brand-50 p-4"><div class="flex items-center gap-3"><span class="grid size-11 place-items-center rounded-xl bg-white text-brand-600"><lucide-icon [img]="FileText" /></span><div class="min-w-0 flex-1"><p class="truncate text-sm font-bold">{{selectedFile()?.name}}</p><p class="text-xs text-slate-500">{{fileSize()}}</p></div><button aria-label="Remove file" class="rounded-lg p-2 text-slate-400 hover:bg-white" (click)="clear()"><lucide-icon [img]="X" [size]="18" /></button></div>
 @if (progress()>0) {<div class="mt-4"><div class="mb-2 flex justify-between text-xs font-semibold"><span>{{progress()<100?'Uploading & analyzing…':'Analysis ready'}}</span><span>{{progress()}}%</span></div><div class="h-2 overflow-hidden rounded-full bg-white"><div class="h-full rounded-full bg-gradient-to-r from-brand-500 to-mint transition-all duration-500" [style.width.%]="progress()"></div></div></div>}
 @if (progress()===0) {<button class="mt-4 w-full rounded-xl bg-ink px-4 py-3 text-sm font-bold text-white hover:bg-slate-700" (click)="analyze()">Analyze my resume</button>}</div>}
 @if(error()){<p class="mt-3 text-sm font-medium text-red-600" role="alert">{{error()}}</p>}
</section>`,host:{class:'block'}})
export class ResumeUploadComponent { readonly progress=input(0); readonly upload=output<File>(); readonly UploadCloud=UploadCloud; readonly FileText=FileText; readonly X=X; readonly isDragging=signal(false); readonly selectedFile=signal<File|null>(null); readonly error=signal(''); readonly fileSize=()=>{const f=this.selectedFile();return f?`${(f.size/1024/1024).toFixed(1)} MB`:''};
 onDragOver(e:DragEvent){e.preventDefault();this.isDragging.set(true)} onDrop(e:DragEvent){e.preventDefault();this.isDragging.set(false);const f=e.dataTransfer?.files[0];if(f)this.validate(f)} onFileInput(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(f)this.validate(f)} private validate(f:File){const ext=f.name.split('.').pop()?.toLowerCase();if(!['pdf','docx'].includes(ext??'')){this.error.set('Please select a PDF or DOCX file.');return}if(f.size>10*1024*1024){this.error.set('File must be smaller than 10 MB.');return}this.error.set('');this.selectedFile.set(f)} analyze(){const f=this.selectedFile();if(f)this.upload.emit(f)} clear(){this.selectedFile.set(null);this.error.set('')}
}
