import { Component, inject, input, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Bot, Check, Clipboard, LucideAngularModule, MessageCircle, Minimize2, Send, Sparkles, Trash2 } from 'lucide-angular';
import { ChatBotService } from '../../services/chat-bot.service';
@Component({selector:'app-ai-bot',standalone:true,imports:[FormsModule,LucideAngularModule],template:`
<button aria-label="Open AI career coach" class="fixed bottom-6 right-6 z-40 flex items-center gap-3 rounded-full bg-ink p-2.5 pr-5 text-sm font-bold text-white shadow-2xl transition hover:-translate-y-1" (click)="open.set(true)"><span class="grid size-10 place-items-center rounded-full bg-brand-600"><lucide-icon [img]="MessageCircle" [size]="20"/></span><span class="hidden sm:inline">Ask AI Coach</span><i class="absolute right-1 top-0 size-3 rounded-full border-2 border-ink bg-emerald-400"></i></button>
@if(open()){<div class="fixed inset-0 z-40 bg-slate-950/20 sm:hidden" (click)="open.set(false)"></div><aside class="fixed inset-x-3 bottom-3 z-50 flex h-[min(720px,calc(100vh-24px))] flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl sm:inset-x-auto sm:bottom-6 sm:right-6 sm:w-[410px]" aria-label="AI career coach chat">
<header class="flex items-center gap-3 border-b border-slate-200 bg-brand-50 p-4"><span class="relative grid size-11 place-items-center rounded-xl bg-brand-600 text-white"><lucide-icon [img]="Bot"/><i class="absolute -bottom-0.5 -right-0.5 size-3 rounded-full border-2 border-white bg-emerald-400"></i></span><div class="flex-1"><h2 class="text-sm font-bold text-slate-950">Resume AI Coach</h2><p class="text-xs text-emerald-600">Online · Knows your resume</p></div><button class="rounded-lg p-2 text-slate-400 hover:bg-white" aria-label="Clear chat" (click)="chat.clearChat()"><lucide-icon [img]="Trash2" [size]="17"/></button><button class="rounded-lg p-2 text-slate-400 hover:bg-white" aria-label="Minimize chat" (click)="open.set(false)"><lucide-icon [img]="Minimize2" [size]="17"/></button></header>
<div class="flex-1 space-y-4 overflow-y-auto bg-slate-50/70 p-4">@for(message of chat.messages();track message.id){<div class="flex" [class.justify-end]="message.role==='user'"><div class="max-w-[85%]"><div class="rounded-2xl px-4 py-3 text-sm leading-relaxed" [class.rounded-br-md]="message.role==='user'" [class.bg-ink]="message.role==='user'" [class.text-white]="message.role==='user'" [class.rounded-bl-md]="message.role==='assistant'" [class.border]="message.role==='assistant'" [class.bg-white]="message.role==='assistant'">{{message.content}}</div>@if(message.role==='assistant'&&message.id!=='welcome'){<div class="mt-2 flex gap-2"><button class="flex items-center gap-1 rounded-lg border bg-white px-2 py-1 text-[11px] font-bold text-slate-500" (click)="copy(message.content,message.id)"><lucide-icon [img]="copied()===message.id?Check:Clipboard" [size]="12"/>{{copied()===message.id?'Copied':'Copy suggestion'}}</button><button class="flex items-center gap-1 rounded-lg bg-brand-50 px-2 py-1 text-[11px] font-bold text-brand-600"><lucide-icon [img]="Sparkles" [size]="12"/>Apply to resume</button></div>}</div></div>}@if(chat.isTyping()){<div class="flex gap-1"><i class="size-2 animate-bounce rounded-full bg-slate-400"></i><i class="size-2 animate-bounce rounded-full bg-slate-400"></i><i class="size-2 animate-bounce rounded-full bg-slate-400"></i></div>}</div>
<div class="border-t bg-white p-4"><div class="mb-3 flex gap-2 overflow-x-auto">@for(prompt of prompts;track prompt){<button class="whitespace-nowrap rounded-full bg-slate-100 px-3 py-1.5 text-[11px] font-semibold text-slate-600" (click)="draft=prompt">{{prompt}}</button>}</div><form class="flex items-end gap-2 rounded-2xl border p-2 focus-within:border-brand-400" (submit)="send($event)"><textarea name="message" [(ngModel)]="draft" rows="1" class="min-h-10 flex-1 resize-none px-2 py-2 text-sm outline-none" placeholder="Ask about your resume…"></textarea><button type="submit" class="grid size-10 place-items-center rounded-xl bg-brand-600 text-white" [disabled]="!draft.trim()"><lucide-icon [img]="Send" [size]="17"/></button></form><p class="mt-2 text-center text-[10px] text-slate-400">AI can make mistakes. Review suggestions before applying.</p></div></aside>}`})
export class AiBotComponent{readonly resumeId=input<number|null>(null);readonly chat=inject(ChatBotService);readonly open=signal(false);readonly copied=signal('');readonly prompts=['Improve my summary','Add stronger metrics','Tailor for this role'];draft='';readonly MessageCircle=MessageCircle;readonly Bot=Bot;readonly Trash2=Trash2;readonly Minimize2=Minimize2;readonly Send=Send;readonly Clipboard=Clipboard;readonly Sparkles=Sparkles;readonly Check=Check;
send(e:Event){e.preventDefault();const value=this.draft.trim();if(!value)return;this.draft='';this.chat.sendMessage(value,this.resumeId()).subscribe({error:response=>this.chat.addLocalReply(response.error?.message??'The AI coach is unavailable. Check the Groq API key in the backend configuration.')})}async copy(text:string,id:string){await navigator.clipboard.writeText(text);this.copied.set(id);setTimeout(()=>this.copied.set(''),1500)}}
